version: '3.8'

services:
  mongodb:
    image: mongo:8.0
    container_name: mongo_db
    ports:
      - "27020:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    volumes:
      - mongodb_data:/data/db
volumes:
  mongodb_data: