version: "3.8"

services:
  board-service:
    container_name: board-service
    image: ${DOCKER_USERNAME}/board-service:latest  # Docker Hub 이미지 사용
    ports:
      - "8082:8082"
    env_file:
      - .env
    networks:
      - backend

networks:
  backend:
    external: true