version: "3.8"

services:
  board-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      EUREKA_HOST: ${EUREKA_HOST}
    restart: unless-stopped
    networks:
      - backend

networks:
  backend:
    driver: bridge