version: "3.8"

services:
  board-service:
    container_name: board-service
    ports:
      - "8081:8081"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - backend

networks:
  backend:
    driver: bridge