server:
  port: 8082
  forward-headers-strategy: framework

spring:
  config:
    import: optional:dotenv:.env
  application:
    name: board-service
  profiles:
    active: dev

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui/index.html