spring:
  config:
    import: optional:dotenv:.env

  data:
    mongodb:
      uri: mongodb+srv://${EC2_MONGOID}:${EC2_MONGOPW}@spharos.uxnx7ao.mongodb.net/piece_of_cake?retryWrites=true&w=majority
      auto-index-creation: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${EC2_HOST}:8761/eureka/

openai:
  api:
    model: gpt-4o
    key: ${GPT_API_KEY}
    temperature: 0.0
    maxTokens: 500

    url:
      model: https://api.openai.com/v1/models
      model-list: https://api.openai.com/v1/models
      prompt: https://api.openai.com/v1/chat/completions