spring:
  datasource:
    url: jdbc:mysql://localhost:3306/board_db
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 12341234

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/