server:
  port: 8081
  forward-headers-strategy: framework

# Spring Application ??
spring:
  main:
    web-application-type: reactive
  application:
    name: board-service

  datasource:
    url: jdbc:mysql://${EUREKA_HOST}:3306/piece_of_cake
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${EUREKA_HOST}:8761/eureka/