spring:
  data:
    mongodb:
      uri: mongodb://admin:admin123@127.0.0.1:27020/board-service?authSource=admin
      auto-index-creation: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/