spring:
  config:
    import: optional:dotenv:.env
  data:
    mongodb:
      uri: mongodb://${EC2_MONGOID}:${EC2_MONGOPW}@${EC2_HOST}:27017/piece_of_cake
      auto-index-creation: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${EC2_HOST}:8761/eureka/